apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
